# Generated by Django 5.2.3 on 2025-07-28 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'Product_Gallery', 'verbose_name_plural': 'Product Gallery'},
        ),
    ]
