# Generated by Django 5.2.3 on 2025-07-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='+1-864-678-6969', max_length=100, unique=True),
        ),
    ]
